export const CREATE_DIRECTORY = 'DIRECTORY/CREATE';
export const DELETE_DIRECTORY = 'DIRECTORY/DELETE';
export const RESTORE_DIRECTORY = 'DIRECTORY/RESTORE';

export const PLAY_MUSIC = 'MUSIC/PLAY';
export const STOP_MUSIC = 'MUSIC/STOP';
