export const CREATE_DIRECTORY = 'DIRECTORY/CREATE';
export const DELETE_DIRECTORY = 'DIRECTORY/DELETE';
export const RESTORE_DIRECTORY = 'DIRECTORY/RESTORE';

export const ADD_NETWORK = 'NETWORK/ADD';
export const REMOVE_NETWORK = 'NETWORK/REMOVE';
export const RESTORE_NETWORK = 'NETWORK/RESTORE';

export const PLAY_MUSIC = 'MUSIC/PLAY';
export const STOP_MUSIC = 'MUSIC/STOP';
